[build]
target = "avr-specs/avr-attiny2313.json"

[target.'cfg(target_arch = "avr")']
runner = "avrdude -c diecimila -p t2313 -U flash:w:./target/avr-attiny2313/release/clock-firmware.elf:e"

[unstable]
build-std = ["core"]
